/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSdkRouteImport } from './routes/docs/sdk'
import { Route as DocsRequestTypesRouteImport } from './routes/docs/request-types'
import { Route as DocsReferenceRouteImport } from './routes/docs/reference'
import { Route as DocsReactRouteImport } from './routes/docs/react'
import { Route as DocsPayloadRouteImport } from './routes/docs/payload'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSdkRoute = DocsSdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRequestTypesRoute = DocsRequestTypesRouteImport.update({
  id: '/request-types',
  path: '/request-types',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReferenceRoute = DocsReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReactRoute = DocsReactRouteImport.update({
  id: '/react',
  path: '/react',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPayloadRoute = DocsPayloadRouteImport.update({
  id: '/payload',
  path: '/payload',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/sponsors': typeof SponsorsRoute
  '/docs/payload': typeof DocsPayloadRoute
  '/docs/react': typeof DocsReactRoute
  '/docs/reference': typeof DocsReferenceRoute
  '/docs/request-types': typeof DocsRequestTypesRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/download': typeof DownloadRoute
  '/sponsors': typeof SponsorsRoute
  '/docs/payload': typeof DocsPayloadRoute
  '/docs/react': typeof DocsReactRoute
  '/docs/reference': typeof DocsReferenceRoute
  '/docs/request-types': typeof DocsRequestTypesRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/sponsors': typeof SponsorsRoute
  '/docs/payload': typeof DocsPayloadRoute
  '/docs/react': typeof DocsReactRoute
  '/docs/reference': typeof DocsReferenceRoute
  '/docs/request-types': typeof DocsRequestTypesRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/docs'
    | '/download'
    | '/sponsors'
    | '/docs/payload'
    | '/docs/react'
    | '/docs/reference'
    | '/docs/request-types'
    | '/docs/sdk'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/download'
    | '/sponsors'
    | '/docs/payload'
    | '/docs/react'
    | '/docs/reference'
    | '/docs/request-types'
    | '/docs/sdk'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/docs'
    | '/download'
    | '/sponsors'
    | '/docs/payload'
    | '/docs/react'
    | '/docs/reference'
    | '/docs/request-types'
    | '/docs/sdk'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  DocsRoute: typeof DocsRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sdk': {
      id: '/docs/sdk'
      path: '/sdk'
      fullPath: '/docs/sdk'
      preLoaderRoute: typeof DocsSdkRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/request-types': {
      id: '/docs/request-types'
      path: '/request-types'
      fullPath: '/docs/request-types'
      preLoaderRoute: typeof DocsRequestTypesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/reference': {
      id: '/docs/reference'
      path: '/reference'
      fullPath: '/docs/reference'
      preLoaderRoute: typeof DocsReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/react': {
      id: '/docs/react'
      path: '/react'
      fullPath: '/docs/react'
      preLoaderRoute: typeof DocsReactRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/payload': {
      id: '/docs/payload'
      path: '/payload'
      fullPath: '/docs/payload'
      preLoaderRoute: typeof DocsPayloadRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsPayloadRoute: typeof DocsPayloadRoute
  DocsReactRoute: typeof DocsReactRoute
  DocsReferenceRoute: typeof DocsReferenceRoute
  DocsRequestTypesRoute: typeof DocsRequestTypesRoute
  DocsSdkRoute: typeof DocsSdkRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsPayloadRoute: DocsPayloadRoute,
  DocsReactRoute: DocsReactRoute,
  DocsReferenceRoute: DocsReferenceRoute,
  DocsRequestTypesRoute: DocsRequestTypesRoute,
  DocsSdkRoute: DocsSdkRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
